B2C_ACCOOUNTS_MANAGER/Areas/Sacco/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Mvc;
using B2C_ACCOOUNTS_MANAGER.Functions;
using B2C_ACCOOUNTS_MANAGER.Models;
using B2C_ACCOOUNTS_MANAGER.Models.UOW;
using System.Drawing;

namespace B2C_ACCOOUNTS_MANAGER.Areas.Sacco.Controllers
{
    [Authorize]
    public class PaymentsController : Controller
    {
        private readonly Repository _repository;
        private readonly UniqueId _uniqueId = new UniqueId();
        private const int PageSize = 25;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        B2C_MANAGEREntities db = new B2C_MANAGEREntities();
        // GET: Sacco/Payments
        public ActionResult Index()
        {
            string user = Common.Classes.Common.ReturnLastUpdateby(false, Request);

            var user_details = db.AspNetUsers.OrderByDescending(p => p.Id).FirstOrDefault(p => p.UserName == user);

            string orgcode = Convert.ToString(user_details.org_code);

            //var payments = db.PaymentTrans.Where(p => p.Approve_Status != 3 && p.org_code == orgcode).ToList();

            var pp = (from x in db.PaymentTrans
                      where (x.Approve_Status != 3 && x.org_code == orgcode)
                      select new PaymentViewModel
                      {
                          Status_Desc = (from xx in db.Status_Options where xx.ID == x.Approve_Status select xx.Status).ToList(),
                          ID = x.ID,
                          orgcode = x.org_code,
                          TransDate = x.TransDate,
                          //ChequeNo = x.ChequeNo,
                          Amount = x.Amount,
                          Status = x.Approve_Status,
                      }).ToList().OrderByDescending(c => c.ID);

            int o_code = Convert.ToInt32(orgcode);

            var bal = db.AmountBals.Single(x => x.org_code == o_code);

            decimal amount = bal.balance;

            decimal smscost1 = Math.Round(Convert.ToDecimal(amount), 2);

            ViewBag.bal = smscost1;

            return View(pp);
        }

        public ActionResult Create()
        {
            ViewBag.organisations = new SelectList(db.Organizations, "org_code", "org_name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PaymentViewModel model, HttpPostedFileBase Chequeimg)
        {
            if (ModelState.IsValid)
            {
                string chequeno = "";

                string user = Common.Classes.Common.ReturnLastUpdateby(false, Request);

                var user_details = db.AspNetUsers.OrderByDescending(p => p.Id).FirstOrDefault(p => p.UserName == user);

                string orgcode = Convert.ToString(user_details.org_code);

                string sysname = "ProT_" + Common.Classes.Common.ReturnDateTimeSingleString();
                try
                {
                    //generate random receipt no
                    char[] charArr = "0123456789".ToCharArray();

                    string strrandom = string.Empty;
                    Random objran = new Random();
                    int noofcharacters = Convert.ToInt32(4);
                    for (int i = 0; i < noofcharacters; i++)
                    {
                        //It will not allow Repetation of Characters
                        int pos = objran.Next(1, charArr.Length);
                        if (!strrandom.Contains(charArr.GetValue(pos).ToString()))
                            strrandom += charArr.GetValue(pos);
                        else
                            i--;
                    }
                    string str_random = "KE" + "-" + strrandom;
                    if (Chequeimg != null)
                    {
                        int clength = Chequeimg.ContentLength;
                        byte[] data = new byte[Chequeimg.ContentLength];
                        Chequeimg.InputStream.Read(data, 0, Chequeimg.ContentLength);
                        //var trans = db.PaymentTrans.Any(p => p.ChequeNo == model.ChequeNo);
                        var paymenttran = new PaymentTran();
                        //if (!db.PaymentTrans.Any(p => p.ChequeNo == model.ChequeNo))
                        //{
                        paymenttran.org_code = orgcode;
                        paymenttran.TransDate = DateTime.Now;
                        //paymenttran.ChequeNo = model.ChequeNo;
                        paymenttran.Amount = model.Amount;
                        paymenttran.Chequeimg = data;
                        paymenttran.ChequeNo = str_random;
                        paymenttran.Approve_Status = Convert.ToInt32(MyEnums.StatusOption.Added);
                        db.PaymentTrans.Add(paymenttran);
                        TempData["shortM"] = "Created Successfuly";
                        db.SaveChanges();
                        
                    }
                    else
                    {
                        //var img
                        var paymenttran = new PaymentTran();                        
                        paymenttran.org_code = orgcode;
                        paymenttran.TransDate = DateTime.Now;
                        paymenttran.Amount = model.Amount;
                        paymenttran.ChequeNo = str_random;
                        paymenttran.Approve_Status = Convert.ToInt32(MyEnums.StatusOption.Added);
                        db.PaymentTrans.Add(paymenttran);
                        TempData["shortM"] = "Created Successfuly";
                        db.SaveChanges();
                    }
                }
                catch (Exception ex)
                {

                }
                //TempData["shortMessage"] = "Successfully Created";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["shortMessage"] = "Amount Field Is Required";
                return RedirectToAction("Create");
            }
        }

    }
}

B2C_ACCOOUNTS_MANAGER/Areas/Sacco/Views/Payments/Create.cshtml
@model B2C_ACCOOUNTS_MANAGER.Models.PaymentViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/admin1.cshtml";
}



@{
    var message = TempData["shortMsg"] ?? string.Empty;    
}

<style type="text/css">
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
        display: inline;
    }
</style>

<span style="color: red">@TempData["shortMessage"]</span>
<br />
<div class="page-header">
    <h1>
        Payment
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Create
        </small>
    </h1>
</div>
<br />
<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Create Application Details</h3>
    </div>
    @using (Html.BeginForm("Create", "Payments", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <br />
        <div class="form-horizontal">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-group">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-9">
                    <img id="user_img" height="313px" width="500px" style="border:solid" />
                </div>
            </div>
            @*<div class="form-group">
                    @Html.LabelFor(model => model.orgcode, new { @class = "col-lg-2 control-label" })
                    <div class="col-lg-10">
                        @Html.DropDownListFor(m => m.orgcode, new SelectList(ViewBag.organisations, "Value", "Text"), null, new { @class = "form-control", @id = "ddlcountry", style = "width:333px" })
                        @Html.ValidationMessageFor(model => model.orgcode, "", new { @class = "text-danger" })
                    </div>
                </div>*@
            <div class="form-group">
                @Html.LabelFor(model => model.Chequeimg, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    <input type="file" class="form-control" name="Chequeimg" id="Chequeimg" onchange=" show(this); " multiple style="width:333px" />
                    @Html.ValidationMessageFor(model => model.Chequeimg, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<div class="form-group">
                    @Html.LabelFor(model => model.ChequeNo, new { @class = "col-lg-2 control-label" })
                    <div class="col-lg-10">
                        @Html.TextBoxFor(model => model.ChequeNo, new { @class = "form-control", style = "width:333px" })
                        @Html.ValidationMessageFor(model => model.ChequeNo, "", new { @class = "text-danger" })
                    </div>
                </div>*@



            @*<div class="form-group">
                @Html.LabelFor(model => model.Amount, new { @class = "col-lg-2 control-label" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", style = "width:333px" })
                    @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                </div>
            </div>*@

               @Html.LabelFor(model => model.Amount, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    <div class="required">
                        @Html.TextBoxFor(model => model.Amount, new { @class = "text-danger", style = "width:333px"})
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                        
                </div>
            <hr style="height: 20px;" />
            <div class="form-group">
                <div class="col-lg-offset-4 col-lg-8">
                    <input type="submit" value="Create" class="btn btn-primary" id="submitform" />
                </div>
            </div>
        </div>








         
    }
</div>

<script type="text/javascript">

   function show(input) {
      if (input.files && input.files[0]) {
      var filerdr = new FileReader();
      filerdr.onload = function (e) {
         $('#user_img').attr('src', e.target.result);
      }
      filerdr.readAsDataURL(input.files[0]);
   }
}
</script> 
 
<script type="text/javascript">
var message = '@message';
if(message)
    alert(message);
</script>  

B2C_ACCOOUNTS_MANAGER/Areas/Sacco/Views/Payments/Index.cshtml
@model IEnumerable<B2C_ACCOOUNTS_MANAGER.Models.PaymentViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/admin1.cshtml";
}
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
@{
    var message = TempData["shortM"] ?? string.Empty;
}


<span style="color: red">@TempData["shortMessage"]</span>
<span style="color: red">@TempData["shortMessage1"]</span>

<div class="page-header">
    <h1>
        Payments
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Upload", "Create")
        </small>
    </h1>
</div>

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Float : @ViewBag.bal</h3>
    </div>
    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Trans Date
                </th>
                @*<th>
                   Cheque Image
                </th>*@
                @*<th>
                    Cheque Number
                </th>*@
                <th>
                    Amount
                </th>
                <th>
                    Status
                </th>
                <th></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Trans Date
                </th>
                @*<th>
               Cheque Image
            </th>*@
                @*<th>
                    Cheque Number
                </th>*@
                <th>
                    Amount
                </th>
                <th>
                    Status
                </th>
                <th></th>
            </tr>
        </tfoot>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TransDate)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.Chequeimg)
                    </td>*@
                    @*<td>
                        @Html.DisplayFor(modelItem => item.ChequeNo)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status_Desc)
                    </td>
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID })*@ 
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
                    </td>
                </tr>
            }
        </tbody>
</table>
</div>
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"> </script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"> </script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"> </script>
<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#example').DataTable();
    });
    // Code that uses other library's $ can follow here.
</script>
<script type="text/javascript">
var message = '@message';
if(message)
    alert(message);
</script>  