B2C_ACCOOUNTS_MANAGER/Models/Saf_Reports.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_ACCOOUNTS_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saf_Reports
    {
        public int ID { get; set; }
        public Nullable<int> Org_Code { get; set; }
        public string Receipt_No { get; set; }
        public Nullable<System.DateTime> Completion_Time { get; set; }
        public Nullable<System.DateTime> Initiation_Time { get; set; }
        public string Details { get; set; }
        public string Transaction_Status { get; set; }
        public string PaidIn { get; set; }
        public Nullable<decimal> Widthrawn { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Reason_Type { get; set; }
        public string Other_Info { get; set; }
    
        public virtual Saf_Reports Saf_Reports1 { get; set; }
        public virtual Saf_Reports Saf_Reports2 { get; set; }
    }
}

B2C_ACCOOUNTS_MANAGER/Areas/Sacco/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using B2C_ACCOOUNTS_MANAGER.Models;
using System.Globalization;
using Microsoft.AspNet.Identity.EntityFramework;
using B2C_ACCOOUNTS_MANAGER.Functions;
using B2C_ACCOOUNTS_MANAGER.Models.UOW;
using B2C_ACCOOUNTS_MANAGER.PDF;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Font = iTextSharp.text.Font;
using Image = iTextSharp.text.Image;
using System.Text.RegularExpressions;

namespace B2C_ACCOOUNTS_MANAGER.Areas.Sacco.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        readonly Logs _logs = new Logs();
        private readonly Repository _repository;
        private readonly UniqueId _uniqueId = new UniqueId();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        B2C_MANAGEREntities db = new B2C_MANAGEREntities();


        // GET: Sacco/Reports
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SafReports()
        {
            return View();
        }
        public ActionResult GetSafPDF(string DueDate = null, string DueDate2 = null)
        {
            string dateone = DueDate + " " + "00:00:00";

            string datetwo = DueDate2 + " " + "23:59:59";

            DateTime dtz = Convert.ToDateTime(dateone);

            DateTime dtx = Convert.ToDateTime(datetwo);

            string user = Common.Classes.Common.ReturnLastUpdateby(false, Request);

            var user_details = db.AspNetUsers.OrderByDescending(p => p.Id).FirstOrDefault(p => p.UserName == user);

            int orgcode = user_details.org_code;

            string code = orgcode.ToString();

            var trans = db.Saf_Reports.Where(p => p.Org_Code == orgcode && p.Completion_Time >= dtz && p.Completion_Time <= dtx).ToList();

            if(trans.Count ==0)
            {
                TempData["errormessage"] = "Reports Cannot be Found";
                return RedirectToAction("SafReports");
            }
            else
            {
                string fpath = Request.ServerVariables["REMOTE_ADDR"];

                var addres = Path.Combine(Server.MapPath("~/Files/"));

                var create_pdf = new CreatePdf();

                create_pdf.WritePdf(fpath, addres, user, dateone, datetwo);

                var file_loc = db.PDF_Loc.OrderByDescending(p => p.ID).FirstOrDefault(p => p.UserId == user_details.Id);

                //Response.AppendHeader("Content-Disposition", "inline; filename=" + file_loc.File_Name + ";");

                //string path = AppDomain.CurrentDomain.BaseDirectory + "App_Data/";

                //return File(file_loc.File_Loc, System.Net.Mime.MediaTypeNames.Application.Pdf, file_loc.File_Name);

                //Response.AppendHeader()
                //return RedirectToAction("Checkpdf");
                var pathToTheFile = file_loc.File_Loc;
                var filestream = new FileStream(pathToTheFile, FileMode.Open, FileAccess.Read);

                return new FileStreamResult(filestream, "application/pdf");
            }

        }     
        public ActionResult PaymentReports()
        {
            return View();
        }
        public ActionResult PrintTransactions(FormCollection form, string DueDate = null, string DueDate2 = null)
        {
            string value = form["Status"].ToString();

            int val = Convert.ToInt32(value);

            string dateone = DueDate + " " + "00:00:00";

            string datetwo = DueDate2 + " " + "23:59:59";

            DateTime dtz = Convert.ToDateTime(dateone);

            DateTime dtx = Convert.ToDateTime(datetwo);

            string user = Common.Classes.Common.ReturnLastUpdateby(false, Request);

            var user_details = db.AspNetUsers.OrderByDescending(p => p.Id).FirstOrDefault(p => p.UserName == user);

            int orgcode = user_details.org_code;

            string code = orgcode.ToString();

            var trans = db.PaymentTrans.Where(p => p.org_code == code && p.TransDate >= dtz && p.TransDate <= dtx && p.Approve_Status == val).ToList();

            if(trans.Count == 0)
            {
                TempData["errormessage"] = "Reports Cannot be Found";
                return RedirectToAction("PaymentReports");
            }
            else
            {
                string fpath = Request.ServerVariables["REMOTE_ADDR"];

                var addres = Path.Combine(Server.MapPath("~/Files/"));

                var paymentreport = new CreatePdf();

                paymentreport.WriteTranPdf(fpath, addres, user, val, dateone, datetwo);

                var file_loc = db.PDF_Loc.OrderByDescending(p => p.ID).FirstOrDefault(p => p.UserId == user_details.Id);

                var pathToTheFile = file_loc.File_Loc;
                var filestream = new FileStream(pathToTheFile, FileMode.Open, FileAccess.Read);

                return new FileStreamResult(filestream, "application/pdf");
            }
            
            //return RedirectToAction("Checkpdf");
        }
        public ActionResult SaccoReports()
        {
            return View();
        }
        public ActionResult SaccoTransactions(string DueDate = null, string DueDate2 = null)
        {
            
            string dateone = DueDate + " " + "00:00:00";

            string datetwo = DueDate2 + " " + "23:59:59";

            DateTime dtz = Convert.ToDateTime(dateone);

            DateTime dtx = Convert.ToDateTime(datetwo);

            string user = Common.Classes.Common.ReturnLastUpdateby(false, Request);

            var user_details = db.AspNetUsers.OrderByDescending(p => p.Id).FirstOrDefault(p => p.UserName == user);

            int orgcode = user_details.org_code;

            string code = orgcode.ToString();

            var trans = db.SaccoTrans.Where(p => p.Code == code && p.TransDate >= dtz && p.TransDate <= dtx).ToList();

            if(trans.Count == 0)
            {
                TempData["errormessage"] = "Reports Cannot be Found";
                return RedirectToAction("SaccoReports");
            }
            else
            {
                string fpath = Request.ServerVariables["REMOTE_ADDR"];

                var addres = Path.Combine(Server.MapPath("~/Files/"));

                var paymentreport = new CreatePdf();

                paymentreport.WriteSaccoPdf(fpath, addres, user, dateone, datetwo);

                var file_loc = db.PDF_Loc.OrderByDescending(p => p.ID).FirstOrDefault(p => p.UserId == user_details.Id);

                var pathToTheFile = file_loc.File_Loc;
                var filestream = new FileStream(pathToTheFile, FileMode.Open, FileAccess.Read);

                return new FileStreamResult(filestream, "application/pdf");
            }
            
        }
    }
}

B2C_ACCOOUNTS_MANAGER/Areas/Sacco/Views/Reports/Checkpdf.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("ViewPDF", "Account", FormMethod.Post))
    {
        <a href="javascript:;" onclick="document.forms[0].submit();">View PDF</a>
        <hr />
        @Html.Raw(TempData["Embed"])
    }
</body>
</html>

B2C_ACCOOUNTS_MANAGER/Areas/Sacco/Views/Reports/PaymentReports.cshtml
@model B2C_ACCOOUNTS_MANAGER.Models.Search
@{
    ViewBag.Title = "SafReports";
    Layout = "~/Views/Shared/admin1.cshtml";

}


@{
    var message = TempData["errormessage"] ?? string.Empty;
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>

<br />
<div class="page-header">
    <h1>
        Reports
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Create
        </small>
    </h1>
</div>



<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Generate Transaction Report</h3>
    </div>
    <hr />
    @using (Html.BeginForm("PrintTransactions", "Reports", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="form-group">
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <label>From:</label>
                </div>
                <div class="col-md-4">
                    <input name="DueDate" type="date" id="datepicker" class="form-control" required/>
                </div>

            </div>
        </div>
        <br />
        <div class="row">
            <div class="form-group">
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <label>To:</label>
                </div>
                <div class="col-md-4">
                    <input name="DueDate2" type="date" id="datepicker" class="form-control" required/>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="form-group">
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <label>Status:</label>
                </div>
                <div class="col-md-4">
                    @Html.DropDownList("Status", new List<SelectListItem>

                    {
                        new SelectListItem {Text = "Approved", Value = "2"},
                        new SelectListItem {Text = "Added", Value = "1"},
                        new SelectListItem {Text = "Rejected", Value = "5"},
                    }, new { @class = "form-control", style = "width:333px", required= "required" })
                </div>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                    <input type="submit" value="Search" class="btn btn-primary" id="submitform" />
                </div>
            </div>
        </div>
        <br />
    }
</div>
<script type="text/javascript">
    $(function () {
        $("#datepicker").datepicker();
    });
</script>
<script type="text/javascript">
var message = '@message';
if(message)
    alert(message);
</script>

B2C_ACCOOUNTS_MANAGER/Areas/Sacco/Views/Reports/SaccoReports.cshtml
@model B2C_ACCOOUNTS_MANAGER.Models.Search
@{
    ViewBag.Title = "SafReports";
    Layout = "~/Views/Shared/admin1.cshtml";

}


@{
    var message = TempData["errormessage"] ?? string.Empty;
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>

<br />
<div class="page-header">
    <h1>
        Reports
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Create
        </small>
    </h1>
</div>



<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Generate Transaction Report</h3>
    </div>
    <hr />
    @using (Html.BeginForm("SaccoTransactions", "Reports", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="form-group">
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <label>From:</label>
                </div>
                <div class="col-md-4">
                    <input name="DueDate" type="date" id="datepicker" class="form-control" required/>
                </div>

            </div>
        </div>
        <br />
        <div class="row">
            <div class="form-group">
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <label>To:</label>
                </div>
                <div class="col-md-4">
                    <input name="DueDate2" type="date" id="datepicker" class="form-control" required/>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                    <input type="submit" value="Search" class="btn btn-primary" id="submitform" />
                </div>
            </div>
        </div>
        <br />
    }
</div>
<script type="text/javascript">
    $(function () {
        $("#datepicker").datepicker();
    });
</script>
<script type="text/javascript">
var message = '@message';
if(message)
    alert(message);
</script>

B2C_ACCOOUNTS_MANAGER/Areas/Sacco/Views/Reports/SafReports.cshtml
@model B2C_ACCOOUNTS_MANAGER.Models.Search
@{
    ViewBag.Title = "SafReports";
    Layout = "~/Views/Shared/admin1.cshtml";

}

@{
    var message = TempData["errormessage"] ?? string.Empty;
}


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>

<br />
<div class="page-header">
    <h1>
        Reports
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Create
        </small>
    </h1>
</div>



<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Generate Transaction Report</h3>
    </div>
<hr />
@using (Html.BeginForm("GetSafPDF", "Reports", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="form-group">
            <div class="col-md-1">
            </div>
        <div class="col-md-1">
            <label>From:</label>
         </div>
            <div class="col-md-4">
                <input name="DueDate" type="date" id="datepicker" class="form-control" required/>
         </div>
                
         </div>
         </div>
         <br/>
        <div class="row">
            <div class="form-group">
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <label>To:</label>
                </div>
                <div class="col-md-4">
                    <input name="DueDate2" type="date" id="datepicker" class="form-control" required />
                </div>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                    <input type="submit" value="Search" class="btn btn-primary" id="submitform" />
                </div>
            </div>
        </div>
        <br/>
}
        </div>
<script type="text/javascript">
    $(function () {
        $("#datepicker").datepicker();
    });
</script>
<script type="text/javascript">
var message = '@message';
if(message)
    alert(message);
</script>